/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Inscription (void);
GtkWidget* create_Authentification (void);
GtkWidget* create_Espace_d_administrateur (void);
GtkWidget* create_modifier (void);
GtkWidget* create_services (void);
GtkWidget* create_captdef (void);
GtkWidget* create_options (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_clubs0 (void);
GtkWidget* create_modifc (void);
GtkWidget* create_ajoutc (void);
GtkWidget* create_message (void);
GtkWidget* create_confirmation (void);
GtkWidget* create_options_clubs (void);
GtkWidget* create_Espace_technicien (void);
GtkWidget* create_Ajouter_un_capteur (void);
GtkWidget* create_modifier_un_capteur (void);
GtkWidget* create_afficher_alarme (void);
GtkWidget* create_confirmation_capteur (void);
GtkWidget* create_affiche (void);
GtkWidget* create_ajout (void);
GtkWidget* create_supprime (void);
GtkWidget* create_aceuil (void);
GtkWidget* create_modification (void);
GtkWidget* create_verification (void);
GtkWidget* create_repture (void);
GtkWidget* create_Gestiondemenu (void);
GtkWidget* create_Ajouter_menu (void);
GtkWidget* create_Modifier_menu (void);
GtkWidget* create_Supprimer_menu (void);
GtkWidget* create_Quiter (void);
GtkWidget* create_meuilleur (void);
GtkWidget* create_WELCOME (void);
GtkWidget* create_ajoutfoyer (void);
GtkWidget* create_modiffoyer (void);
GtkWidget* create_affichefoyer (void);
GtkWidget* create_niveau (void);
GtkWidget* create_ajoutrec (void);
GtkWidget* create_modif_rec (void);
GtkWidget* create_supression (void);
GtkWidget* create_rectab (void);
GtkWidget* create_recordre (void);
GtkWidget* create_window1 (void);
